//import { Inter } from "next/font/google";
import "./globals.css";

//const inter = Inter({ subsets: ["Ubuntu"] });

export const metadata = {
  title: "Netflix CLone",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
      {/* className={inter.className} */}
    </html>
  );
}
